### PR TITLE
Settings Page UI

### PR DESCRIPTION
**Pull request by MatthiasReumann**
### Motivation and Context
Update settings page UI for consistency with other pages.

### Description
- Update CSS/HTML. 
- Decrease header footprint, i.e. only import files which are absolutely necessary.

### Steps for Testing
- 1 Account

1. Log in
2. Navigate to settings page
3. Update name, playback speed, etc.
4. Should work
5. 🚀

### Screenshots
Screenshot 2023-09-07 at 07 45 38

### CODE REVIEW

**Comment by alexanderstephan** [comment]
The UI itself looks really good. However, I noticed that the menu disappears in the upper right corner. Is that intended?

**Reference**:
image

**Comment by MatthiasReumann** [comment]
> The UI itself looks really good. However, I noticed that the menu disappears in the upper right corner. Is that intended?
> 
> **Reference**: image

Yup. Same for the info pages. I thought that it makes sense to minimize the footprint of the go-template (i.e. include `.User` object) in order to make it more easy to migrate to a REST-only approach.

**Comment by alexanderstephan** [comment]
Okay, I see 👍 In any case, people can just use the back button in their browser.

**Review by joschahenningsen — APPROVED** [review]
:heart:

**Pull request merged**
