### PR TITLE
Remove Google Cast toggle

### PR DESCRIPTION
**Pull request by alexanderstephan**
Simply removes the Google Cast setting as the feature is probably not coming any time soon.

### CODE REVIEW

**Review by joschahenningsen — CHANGES_REQUESTED** [review]
Agree 👍 can you also remove the route for setting this, the setting type and write a quick migration that drops all settings with this type so they don't cause problems later?

**Comment by alexanderstephan** [comment]
Thanks for the hint, I completely missed that part. :pray:  Do I have to generate anything in this case?

**Comment by joschahenningsen** [comment]
You can write a migration by hand, have a look at https://github.com/joschahenningsen/TUM-Live/blob/dev/dao/migrations/202201280.go

**Comment by alexanderstephan** [comment]
I used an unscoped delete to keep the DB clean, I hope it's not overkill.

**Comment by joschahenningsen** [comment]
> I used an unscoped delete to keep the DB clean, I hope it's not overkill.

Nope thats perfect here!

**Review by joschahenningsen — APPROVED** [review]

**Pull request merged**
