### PR TITLE
Replace name with lrz ID on welcome message

### PR DESCRIPTION
**Pull request by ghost**
Moin $deadname, nice to see you!

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Is the thought behind this that the name you're seeing on the start page is not the one you actually go by? Or is there a legitimate reason you need to see your lrz id?

The issue here is that not all users have an lrz id, if this was only about **not** getting called $deadname, we should work on #358 soon and let users decide how they want to be called.

**Comment by just-max** [comment]
I know that the Informatics Zulip server has already made it possible to use a preferred name. Since #358 seems to be a ways off, maybe we could have something temporary?

Since the name is also displayed in the chat, this can't just be a client side change. Would changing it then require approval from an administrator (like on the Zulip server)? Of course it should be as easy as possible, but if left open people would probably start using nicknames, or worse >:(

Alternatively I could pick up #358 (but it would take a while longer, though)

**Comment by joschahenningsen** [comment]
I hear Y'all, being called a name you don't identify with sucks. I'll move #358 up my priority list and start working on this!

**Comment by joschahenningsen** [comment]
I thought of preventing misuse by limiting the name changing to something like once per month or semester.

**Comment by just-max** [comment]
Ahh thanks :)
Sounds good, I think students will be reasonable with something like that.

**Comment by joschahenningsen** [comment]
fyi, I removed the name from the start page until #462 is merged :)

**Pull request closed without merging**
