### PR TITLE
Bundle version revision into executable

### PR DESCRIPTION
**Pull request by max-ae**
Followup to #74 

This PR makes changes to bake the revision at build right into the executable instead of using an env-file that could very well change at runtime. 

One question remains: does the server merge local env commits into the local repository before or after the `make bundle` target? If before, `HEAD` in the Makefile again needs to be changed to `origin/HEAD`, otherwise fine as-is.

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Nice, Appreciate it!

> does the server merge local env commits into the local repository before or after the make bundle target? 

Before.

Imo, the version tag variable should live in the tools package in case I need to access it from eg. the dao at some point. (There already is a variable for it in tools.Cfg, I just didn't use it for some reason)

**Review by joschahenningsen — APPROVED** [review]
Until I removed dependencies from tools to dao this is perfectly fine :) Thanks for helping out!

**Comment by max-ae** [comment]
Nice! 
I just did not get the chance to change `HEAD` to `origin/HEAD` 😅 As-is, this will now again use the revision of the local merge commit...

**Comment by joschahenningsen** [comment]
Just changed it, thanks for the heads up

**Pull request merged**
