### PR TITLE
Fix VoD Ordering

### LINKED ISSUE #240: Only months change order
If you change the order of the lectures, it only changes the order of the months but not of the lectures within.
No matter if the months are ascending or descending, the newest lecture of a month is always on top.

Expected behavior:
The lectures within a month should also change order.
Ascending Order
Descending Order

### PR DESCRIPTION
**Pull request by MatthiasReumann**
Closes #240

### CODE REVIEW

**Review by joschahenningsen — CHANGES_REQUESTED** [review]
Looks good!
This seems to contain changes from #239 though, could you update your branch?

**Comment by MatthiasReumann** [comment]
> Looks good!
> This seems to contain changes from #239 though, could you update your branch?

Ah, crap. Seems like I created the new branch on the hamburger one. Any idea on how to solve that? 😅

**Comment by joschahenningsen** [comment]
I think `git merge dev` on your branch should do

**Review by joschahenningsen — APPROVED** [review]
Ahh already merged, thanks!

**Pull request merged**
