### PR TITLE
1306 usercontext menu inconsistent padding

### LINKED ISSUE #1306: userContext menu inconsistent padding
**Describe the bug**
the userContext menu menu entries have padding different from the header. I feel like the header has the visually better padding
image
the header has padding `0.5rem 1rem`, the menu entries have `0.5rem[ 0.5rem]`

**To Reproduce**
1. Go to Startpage
2. Click on the user icon at the top right

**Expected behavior**
image
edited so that both the header and the entries have padding `0.5rem 1rem`

**Desktop (please complete the following information):**
 - OS: ubuntu 23
 - Browser: Firefox 121
 
 **Additional info**
 my browser shows me this in home.css in lines 2752-2755 and 2768-2775 respectively
 Frankly I couldnt find the culprit in the repo. Im _assuming_ its tailwinds
```css
.tum-live-menu>header {
  border-bottom-width:1px;
  padding:.5rem 1rem
}
```
 ```css
 .tum-live-menu .tum-live-menu-item {
  margin-top:.5rem;
  margin-bottom:.5rem;
  display:flex;
  width:100%;
  align-items:center;
  padding:.5rem /* this is the problem */
}
```

### PR DESCRIPTION
**Pull request by YiranDuan721**
### Motivation and Context
To improve the look of the user menu.

### Description

1. Align padding of header and items in the menu (fixes #1306)
2. Reduce the space between icon and text in each item button
3. Adjust the size and position of theme selections, making them more like sub-items of the item "theme" in the menu

### Step for testing
1. Remove "web/assets/css-dist"
2. Run `npm i` under "web/"
3. Run DB from docker; Build and run TUMLive-Backend
4. Access localhost:8081, clear all website data and refresh website

### Screenshots

| Before | After |
| ------ | ----- |
| <p align=center> </p>| <p align=center></p> |

### CODE REVIEW

**Review by SebiWrn — CHANGES_REQUESTED** [review]
I think the Admin Button is still slightly off.

**Comment by YiranDuan721** [comment]
> I think the Admin Button is still slightly off.

Thank you, I've made one more change. What do you think of this:
<div align=center>
 

</div>

**Comment by SebiWrn** [comment]
I think the icon is still a bit more on the left than the other icons

**Comment by meandaD** [comment]
> I think the icon is still a bit more on the left than the other icons

Maybe that's because the hammer icon is wider than other icons? I think the icons are vertically aligned in the center.

**Comment by YiranDuan721** [comment]
> I think the icon is still a bit more on the left than the other icons

Yes indeed... They should be vertically aligned in the center now:

**Review by SebiWrn — APPROVED** [review]
Looking much better now

**Pull request merged**
