### PR TITLE
Added headers to config for fixing ase.in.tum

### PR DESCRIPTION
**Pull request by SebiWrn**
### Motivation and Context
Fixed ticket of ase in tum

### Description
Added headers to config

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Which headers do they need?

**Comment by SebiWrn** [comment]
Access-Control-Allow-Origin with value ase.in.tum.de, because they told us else they can't edit the jframes on their website with javascript

**Review by KemalKrKX — APPROVED** [review]
Looks good.

**Review by joschahenningsen — COMMENTED** [review]
This could also be handled using traefik https://doc.traefik.io/traefik/middlewares/http/headers/

**Comment by SebiWrn** [comment]
Ok so we shouldn't do it with gin directly?

**Pull request closed without merging**
