### PR TITLE
1094 list view in new UI

### LINKED ISSUE #1094: List View in new UI
Hey,

it would be nice to have a toggle for switching between a "Thumbnail View" and "List View".
A Thumbnail View is useful for finding out the topic of a lecture (assuming the lecture has only a timestamp), while a
List View (similar to the old UI) is much more convenient for finding specific lectures without clicking through pages of thumbnails (less Pagination)

### PR DESCRIPTION
**Pull request by SebiWrn**
### Motivation and Context
Adds a List View to the course view.

### Description
You can now switch between the thumbnail and list view in the course page.

### Steps for Testing
Prerequisites:
- 1 Account
- 1 course with multiple lectures

1. Log in
2. Navigate to a Course
3. Switch to list view

### Screenshots
Default View:
image

List View:
image

### CODE REVIEW

**Review by SebiWrn — COMMENTED** [review]
Somehow previous commits are also in this PR, but only really changed files are home.gohtml and course.ts, everything else is already merged into dev

**Comment by YiranDuan721** [comment]
Currently, the status of whether the list view is displayed is reset when the page is accessed again. I would prefer it to be preserved like the other options. I can see that the state "listView" is indeed preserved in the browser's local storage, but it doesn't look like it's being restored properly when the page loads or reloads.

**Comment by SebiWrn** [comment]
Thank you for your feedback, problem should be fixed now :)

**Review by DawinYurtseven — APPROVED** [review]
looks good!

**Pull request merged**
