### PR TITLE
add test users to testserver comment

### PR DESCRIPTION
**Pull request by joschahenningsen**
### Steps for Testing

1. Is there a comment telling you which users are available?
2. do they work?

### CODE REVIEW

**Comment by alexanderstephan** [comment]
Looks good! The test server works fine, I also tested all user types, which also seemed to work fine. I also see the comment. Is there anything else to do here?

**Comment by joschahenningsen** [comment]
No that's all. I noticed that let's encrypt rate limits based on the base domain (tum.de) so we might have to wait a minute longer from time to time.

**Comment by joschahenningsen** [comment]
Feel free to approve :)

**Comment by alexanderstephan** [comment]
> No that's all. I noticed that let's encrypt rate limits based on the base domain (tum.de) so we might have to wait a minute longer from time to time.

Ah, that's totally ok. :)

**Review by alexanderstephan — APPROVED** [review]
:partying_face:

**Pull request merged**
