### PR TITLE
Fix description markdown

### LINKED ISSUE #729: Description markdown not rendered properly
**Describe the bug**
The Markdown in video descriptions gets reduced to plain text in the video descriptions.

image

image

### PR DESCRIPTION
**Pull request by MatthiasReumann**
### Motivation and Context
- Fixes #729 

### Description
- Increase cutoff length to 256
- Remove truncated variables but keep `truncateHtml` function
- Update UI (a bit)
- Add list css

### Steps for Testing
1. Log in as admin
2. Navigate to a Livestream
3. Update description with lists, etc.
4. Should be changed

### Screenshots

https://user-images.githubusercontent.com/29633518/199230476-800fc3af-7474-44a4-9f05-51384568ddc7.mov

### CODE REVIEW

**Review by joschahenningsen — CHANGES_REQUESTED** [review]
Looks great, thanks! :heart:  I noticed a few quirks though:

- When the description is short (nothing to expand) the cursor is still a pointer when hovering the description
-  Expanding is dependent on the number of characters, could it be the number of lines instead to prevent quirks like this?


https://user-images.githubusercontent.com/44805696/199276033-fdcdd699-0141-4e70-b69e-5fe38f781c08.mp4

We could also go for something like `if (numLines>5 || numChars>100){ // resizable }` but you are  the expert here :)

**Comment by MatthiasReumann** [comment]
> Looks great, thanks! ❤️ I noticed a few quirks though:
> 
> * When the description is short (nothing to expand) the cursor is still a pointer when hovering the description
> * Expanding is dependent on the number of characters, could it be the number of lines instead to prevent quirks like this?
> 
>  out.mp4 
> 
> We could also go for something like `if (numLines>5 || numChars>100){ // resizable }` but you are the expert here :)

Number of lines makes sense. Will have a look into it!

**Comment by MatthiasReumann** [comment]
> Looks great, thanks! ❤️ I noticed a few quirks though:
> 
> * When the description is short (nothing to expand) the cursor is still a pointer when hovering the description
> * Expanding is dependent on the number of characters, could it be the number of lines instead to prevent quirks like this?
> 
>  out.mp4 
> 
> We could also go for something like `if (numLines>5 || numChars>100){ // resizable }` but you are the expert here :)

What do you actually think about going back to using `overflow-y: clip;` again, combined with the cutoff-length?

https://user-images.githubusercontent.com/29633518/199302924-c4c79463-444c-4f1b-a99b-fb7ed12d1640.mov


https://user-images.githubusercontent.com/29633518/199302930-2bddd568-c015-4cb2-b71e-6f37b1214945.mov

**Comment by joschahenningsen** [comment]
Sure, the simplest solution is always the best if it works!

**Review by joschahenningsen — APPROVED** [review]
Thanks!

**Pull request merged**
