### PR TITLE
Regenerate preview images for lectures

### PR DESCRIPTION
**Pull request by alexanderstephan**
This PR enables:
- Generation of thumbnails on demand for a given stream via the admin interface. This includes video section and timeline thumbnails.
- An API endpoint that triggers regeneration of thumbnails for all VoDs. For each VoD path a request is sent to a worker. This has the advantage that we can split the regeneration tasks to different workers.
- A helper program that traverses all streams with VoDs and regenerates thumbnails for them.

### CODE REVIEW

**Review by joschahenningsen — APPROVED** [review]
@alexanderstephan  From my perspective this looks good now, feel free to have another look :)

**Comment by alexanderstephan** [comment]
Yeah, looks great now! 🎉

**Comment by alexanderstephan** [comment]
Ah, just one thing. Have you tested video sections previews?

**Comment by joschahenningsen** [comment]
Let's see what happens :D 

> Ah, just one thing. Have you tested video sections previews?

I have not. How do they relate to this PR? Should they be generated as well?

**Comment by alexanderstephan** [comment]
Yes, they should also get generated. At least there is still code left for that in `RegenerateThumb`.

**Pull request merged**
