### PR TITLE
Add sortable streams

### LINKED ISSUE #261: Sort Streams in admin interface

### PR DESCRIPTION
**Pull request by MatthiasReumann**
- Streams can now be sorted (Default is desc - as it was before, sorry 😅) Closes #261
- Added a "template button" which can be used in #249 for smaller util buttons.

For later copy & paste usage:
```
<button class="border bg-white border-gray-300 rounded w-20 my-auto shadow-sm text-gray-600
                          hover:border-black hover:text-black
                          dark:bg-gray-700 dark:border-gray-800 dark:text-gray-200 dark:hover:border-gray-100
                          dark:hover:text-white" @click="sortAsc = !sortAsc;">
  <span class="text-sm font-semibold uppercase m-auto"
              x-text="sortAsc ? '&#x25B2; asc' : '&#x25BC; desc'">&#x25BC; desc</span>
</button>
```

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Perfect! We should write those templates down somewhere centralized.

Can you make use of alpines `$store` capabilities to persist the preference? 
https://alpinejs.dev/magics/store#single-value-stores

**Comment by joschahenningsen** [comment]
https://alpinejs.dev/plugins/persist looks even more promising actually

**Comment by MatthiasReumann** [comment]
> Perfect! We should write those templates down somewhere centralized.
> 
> Can you make use of alpines `$store` capabilities to persist the preference? https://alpinejs.dev/magics/store#single-value-stores

Oh that's cool. 👍 Didn't know that exists. This also means we could potentially reduce TypeScript code (for example I implemented the storage of the chatOpen value by myself)

**Comment by joschahenningsen** [comment]
> This also means we could potentially reduce TypeScript code (for example I implemented the storage of the chatOpen value by myself)

Yup, that would be a cool follow-up :)

**Review by joschahenningsen — COMMENTED** [review]
Nice, thanks!

**Review by joschahenningsen — APPROVED** [review]

**Pull request merged**
