### PR TITLE
Meilisearch for prefetched courses

### PR DESCRIPTION
**Pull request by joschahenningsen**
### Motivation and Context

The current sql fulltext search is not user friendly. To overcome this issue we can try using meilisearch as discussed here: https://github.com/joschahenningsen/TUM-Live/discussions/814 It even handles typos very well.

### Description

The courses are prefetched and stored in a newly introduced search engine instead of the database. From there we can simply query them. 

### Steps for Testing

Run a local instance of meilisearch like this:
```
docker run -it --rm \
    -p 7700:7700 \
    -e MEILI_MASTER_KEY='MASTER_KEY'\
    -v $(pwd)/meili_data:/meili_data \
    getmeili/meilisearch:v0.30 \
    meilisearch --env="development"
```
Download and extract this json document: 
[prefetchedCourses.zip](https://github.com/joschahenningsen/TUM-Live/files/10145925/prefetchedCourses.zip)

Push it to meilisearch as demo data: 

```
curl \                                      
  -H "Authorization: Bearer MASTER_KEY" -X POST 'http://localhost:7700/indexes/PREFETCHED_COURSES/documents?primaryKey=courseID' \
  -H 'Content-Type: application/json' \
  --data-binary @prefetchedCourses.json
```

Test the search when creating a course 

The import can only be tested with a tum online token so you'll need to trust me on this :P

### Screenshots

https://user-images.githubusercontent.com/44805696/205313794-edae6066-9c8c-4ace-815e-891684570fc1.mp4

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Thanks to @CommanderStorm for the input on this :)

**Comment by alexanderstephan** [comment]
When run `meilisearch` and add the `json` file, I get no results (although all requests are status `200`). Do you have any idea what could be wrong?
I get `[2022-12-02T20:06:08Z INFO  index_scheduler] A batch of tasks was successfully completed.`, so I assume it is added.

**Comment by alexanderstephan** [comment]
I think I get the error `missing_document_id`, which might be related to a broken setup.

**Comment by joschahenningsen** [comment]
Hm I thought the ?primaryKey might do the trick 🤔
I'll check this out tomorrow!

**Comment by joschahenningsen** [comment]
@alexanderstephan I updated the zip file, it should work with the new one :)

**Review by alexanderstephan — APPROVED** [review]
Wow, it really works great. 🎉 The code looks also flawless. 👍

**Pull request merged**
