### PR TITLE
Support AirPlay

### PR DESCRIPTION
**Pull request by MW360**
This PR only contains the AirPlay part only of #436.
Partially resolving #185.

This PR allows to already integrate the AirPlay functionality without the need to wait for the pending changes required by the Google Cast feature.

An AirPlay button is added to the video control bar allowing for AirPlay configuration in custom video player on supported browsers:

IMG_E16C538ECEA1-1

### CODE REVIEW

**Comment by MW360** [comment]
The AirPlay button does not appear in Safari on MacOS.
Maybe this is the case because there is no AirPlay device available.

It would be great if someone with another AirPlay capable receiving device like an Apple TV can check this.

**Comment by joschahenningsen** [comment]
@max-ae Would you mind having a look at [this video](https://test.live.mm.rbg.tum.de/w/airplay/272) and check if airplay is available? :blush:

**Comment by max-ae** [comment]
> @max-ae Would you mind having a look at [this video](https://test.live.mm.rbg.tum.de/w/airplay/272) and check if airplay is available? 😊

Works perfectly! 🎉

**Comment by alexanderstephan** [comment]
Also just tried it on my iPad and it works flawlessly :+1:

**Review by joschahenningsen — APPROVED** [review]
Nice, thanks!

**Pull request merged**
