### PR TITLE
Video Section fixes

### LINKED ISSUE #440: Video Sections: Formatting of Timestamps on Admin Page [Minor Issue]
On the admin page, timestamps of video sections are formatted without trailing zeroes:

image

Expected would be e.g. `00:07:30` or `07:30`

The public display is fine though:

image

### LINKED ISSUE #441: Video Sections: Sections are Sorted by Creation Timestamp, not by Video Timestamp
For example, I added in this last section after all the others, but now it shows at the end of the section list. This applies to the public page were viewers watch the VoD.

image

### PR DESCRIPTION
**Pull request by MatthiasReumann**
Closes #440 
Closes #441

### CODE REVIEW

**Review by joschahenningsen — APPROVED** [review]
Thanks! :heart:

**Comment by just-max** [comment]
Unfortunately on the admin page I still can't see any video sections I've added, see https://github.com/joschahenningsen/TUM-Live/pull/443#issuecomment-1122009921

Watch page:
image

Admin page:
image

**Comment by joschahenningsen** [comment]
I didn't deploy the latest version yet, I usually wait until there's less traffic in case something goes wrong :)

**Comment by just-max** [comment]
Of course, makes sense :)

**Comment by joschahenningsen** [comment]
Should be good now @just-max

**Comment by just-max** [comment]
Looks good, thanks for the speedy fixes

**Pull request merged**
