### PR TITLE
Enh/runner audio normalization

### PR DESCRIPTION
**Pull request by YiranDuan721**
### Motivation and Context
Previous PR: #1230 
As mentioned in #1206: The range of the volume varies across the recordings, which leads to a poorer user experience in some cases, and has caused [problem to the silence-skip feature](https://github.com/TUM-Dev/gocast/issues/1186).

### Description

As discribed in #1230: 
Applies [the loudnorm filter of ffmpeg](https://ffmpeg.org/ffmpeg-filters.html#loudnorm) during transcoding. Parameters are chosen according to [the EBU recommendation R128](https://tech.ebu.ch/publications/r128s3).

Results of some experiments with this method, from [here](https://github.com/TUM-Dev/gocast/issues/1206#issuecomment-1793861080):
> Normalization using the loudnorm filter in FFmpeg has achieved good results: The graphs below show the changes in volume over time for three video recordings, comparing the original version to the normalized version. The stashed red line marks -15dB, which is now used as the threshold for silence detecting -- and is indeed suitable for the normalized audio, according to the result to these experiments.
> 
>   
> The three recordings, after audio normalization, all sound good to me. The volume scatter points in the graph represent the maximum volume of a serial of segments (lasting from 3 to 8.333333 seconds), obtained by the ffmpeg volumedetect filter.

### Steps for Testing

Further tests can be done with the test of the runner.

### CODE REVIEW

**Comment by CommanderStorm** [comment]
@YiranDuan721 (sorry for the ping)

Did this PR resolve the following issues?
- https://github.com/TUM-Dev/gocast/issues/1206
- https://github.com/TUM-Dev/gocast/issues/1186

**Comment by YiranDuan721** [comment]
> @YiranDuan721 (sorry for the ping)

Anytime!

> Did this PR resolve the following issues?
> 
> * [Normalize the volume of recordings #1206](https://github.com/TUM-Dev/gocast/issues/1206)
> * [Entire stream recognized as pause #1186](https://github.com/TUM-Dev/gocast/issues/1186)

It is supposed to have solved #1206, and to be helpful for #1186 in most cases. However, I haven't had time to do more tests on it. I would suggest that more tests should be done for the changes, e.g. transcode some problematic videos with the changes and see if the Pausen can be detected as expected. Saddly, it seems that I myself won't have time to work on it in this semester.

**Comment by MariusAlbrecht** [comment]
the behaviour originally described in #1186 seems to still be as is. In other words: the entirety of https://live.rbg.tum.de/w/sturepfuprover/35614 is still being recognized as one whole skippable section.

@CommanderStorm

**Comment by joschahenningsen** [comment]
this pr was merged into the enh/runner branch, which is an attempt to replace the currently rather unreliable worker. This unfortunately remains work in progress and I have no estimate about the eta. Right now the project is on @DawinYurtseven s plante

**Comment by MariusAlbrecht** [comment]
No problem! I was just going through my open issues to see if any are wrongfully open and then went ahead and answered @/CommanderStorm's question.

**Pull request merged**
